namespace Jenny.Plugins
{
    public class AddFileHeaderPostProcessor : IPostProcessor
    {
        public string Name => "Add file header";
        public int Order => 0;
        public bool RunInDryMode => true;

        public const string AutoGeneratedHeaderFormat =
            @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by {0}.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

        public CodeGenFile[] PostProcess(CodeGenFile[] files)
        {
            foreach (var file in files)
                file.FileContent = string.Format(AutoGeneratedHeaderFormat, file.GeneratorName) + file.FileContent;

            return files;
        }
    }
}
